// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/strfmt"
)

// FindSensorDataBySensorIDAndTimeRangeURL generates an URL for the find sensor data by sensor id and time range operation
type FindSensorDataBySensorIDAndTimeRangeURL struct {
	ID strfmt.UUID

	From strfmt.DateTime
	To   strfmt.DateTime

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FindSensorDataBySensorIDAndTimeRangeURL) WithBasePath(bp string) *FindSensorDataBySensorIDAndTimeRangeURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *FindSensorDataBySensorIDAndTimeRangeURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *FindSensorDataBySensorIDAndTimeRangeURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/sensor/{id}/values"

	id := o.ID.String()
	if id != "" {
		_path = strings.Replace(_path, "{id}", id, -1)
	} else {
		return nil, errors.New("id is required on FindSensorDataBySensorIDAndTimeRangeURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	fromQ := o.From.String()
	if fromQ != "" {
		qs.Set("from", fromQ)
	}

	toQ := o.To.String()
	if toQ != "" {
		qs.Set("to", toQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *FindSensorDataBySensorIDAndTimeRangeURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *FindSensorDataBySensorIDAndTimeRangeURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *FindSensorDataBySensorIDAndTimeRangeURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on FindSensorDataBySensorIDAndTimeRangeURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on FindSensorDataBySensorIDAndTimeRangeURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *FindSensorDataBySensorIDAndTimeRangeURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
