// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/scylladb/scylla-code-samples/iot-care-pet-example/go/cmd/server/models"
)

// FindSensorsByPetIDOKCode is the HTTP code returned for type FindSensorsByPetIDOK
const FindSensorsByPetIDOKCode int = 200

/*FindSensorsByPetIDOK sensors response

swagger:response findSensorsByPetIdOK
*/
type FindSensorsByPetIDOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Sensor `json:"body,omitempty"`
}

// NewFindSensorsByPetIDOK creates FindSensorsByPetIDOK with default headers values
func NewFindSensorsByPetIDOK() *FindSensorsByPetIDOK {

	return &FindSensorsByPetIDOK{}
}

// WithPayload adds the payload to the find sensors by pet Id o k response
func (o *FindSensorsByPetIDOK) WithPayload(payload []*models.Sensor) *FindSensorsByPetIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find sensors by pet Id o k response
func (o *FindSensorsByPetIDOK) SetPayload(payload []*models.Sensor) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindSensorsByPetIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Sensor, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*FindSensorsByPetIDDefault error

swagger:response findSensorsByPetIdDefault
*/
type FindSensorsByPetIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindSensorsByPetIDDefault creates FindSensorsByPetIDDefault with default headers values
func NewFindSensorsByPetIDDefault(code int) *FindSensorsByPetIDDefault {
	if code <= 0 {
		code = 500
	}

	return &FindSensorsByPetIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find sensors by pet id default response
func (o *FindSensorsByPetIDDefault) WithStatusCode(code int) *FindSensorsByPetIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find sensors by pet id default response
func (o *FindSensorsByPetIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find sensors by pet id default response
func (o *FindSensorsByPetIDDefault) WithPayload(payload *models.Error) *FindSensorsByPetIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find sensors by pet id default response
func (o *FindSensorsByPetIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindSensorsByPetIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
