// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// FindSensorDataBySensorIDAndTimeRangeHandlerFunc turns a function with the right signature into a find sensor data by sensor id and time range handler
type FindSensorDataBySensorIDAndTimeRangeHandlerFunc func(FindSensorDataBySensorIDAndTimeRangeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindSensorDataBySensorIDAndTimeRangeHandlerFunc) Handle(params FindSensorDataBySensorIDAndTimeRangeParams) middleware.Responder {
	return fn(params)
}

// FindSensorDataBySensorIDAndTimeRangeHandler interface for that can handle valid find sensor data by sensor id and time range params
type FindSensorDataBySensorIDAndTimeRangeHandler interface {
	Handle(FindSensorDataBySensorIDAndTimeRangeParams) middleware.Responder
}

// NewFindSensorDataBySensorIDAndTimeRange creates a new http.Handler for the find sensor data by sensor id and time range operation
func NewFindSensorDataBySensorIDAndTimeRange(ctx *middleware.Context, handler FindSensorDataBySensorIDAndTimeRangeHandler) *FindSensorDataBySensorIDAndTimeRange {
	return &FindSensorDataBySensorIDAndTimeRange{Context: ctx, Handler: handler}
}

/*FindSensorDataBySensorIDAndTimeRange swagger:route GET /sensor/{id}/values findSensorDataBySensorIdAndTimeRange

Read sensor data

*/
type FindSensorDataBySensorIDAndTimeRange struct {
	Context *middleware.Context
	Handler FindSensorDataBySensorIDAndTimeRangeHandler
}

func (o *FindSensorDataBySensorIDAndTimeRange) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindSensorDataBySensorIDAndTimeRangeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
