// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/scylladb/scylla-code-samples/iot-care-pet-example/go/cmd/server/models"
)

// FindOwnerByIDOKCode is the HTTP code returned for type FindOwnerByIDOK
const FindOwnerByIDOKCode int = 200

/*FindOwnerByIDOK owner response

swagger:response findOwnerByIdOK
*/
type FindOwnerByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Owner `json:"body,omitempty"`
}

// NewFindOwnerByIDOK creates FindOwnerByIDOK with default headers values
func NewFindOwnerByIDOK() *FindOwnerByIDOK {

	return &FindOwnerByIDOK{}
}

// WithPayload adds the payload to the find owner by Id o k response
func (o *FindOwnerByIDOK) WithPayload(payload *models.Owner) *FindOwnerByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find owner by Id o k response
func (o *FindOwnerByIDOK) SetPayload(payload *models.Owner) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindOwnerByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*FindOwnerByIDDefault error

swagger:response findOwnerByIdDefault
*/
type FindOwnerByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindOwnerByIDDefault creates FindOwnerByIDDefault with default headers values
func NewFindOwnerByIDDefault(code int) *FindOwnerByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &FindOwnerByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find owner by id default response
func (o *FindOwnerByIDDefault) WithStatusCode(code int) *FindOwnerByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find owner by id default response
func (o *FindOwnerByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find owner by id default response
func (o *FindOwnerByIDDefault) WithPayload(payload *models.Error) *FindOwnerByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find owner by id default response
func (o *FindOwnerByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindOwnerByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
