version: "3"

networks:
  presto:
    driver: bridge

services:
  metabase:
    restart: always
    image: metabase/metabase:v0.43.7.3
    platform: linux/amd64
    ports:
      - 3000:3000
    networks:
      - presto
    volumes:
      - .docker/metabase/data:/metabase-data
    depends_on:
      - presto

  presto:
    restart: always
    image: ahanaio/prestodb:0.282
    platform: linux/amd64
    ports:
      - 8080:8080
    networks:
      - presto
    volumes:
      - ./resources/etc:/opt/presto-server/etc
    depends_on:
      - scylladb

  scylladb:
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - 9042:9042
    volumes:
      - .docker/scylladb/1:/var/lib/scylla
    networks:
      - presto
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 1s
      retries: 120
      timeout: 1s
