// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindOwnerByIDParams creates a new FindOwnerByIDParams object
// with the default values initialized.
func NewFindOwnerByIDParams() *FindOwnerByIDParams {
	var ()
	return &FindOwnerByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindOwnerByIDParamsWithTimeout creates a new FindOwnerByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindOwnerByIDParamsWithTimeout(timeout time.Duration) *FindOwnerByIDParams {
	var ()
	return &FindOwnerByIDParams{

		timeout: timeout,
	}
}

// NewFindOwnerByIDParamsWithContext creates a new FindOwnerByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindOwnerByIDParamsWithContext(ctx context.Context) *FindOwnerByIDParams {
	var ()
	return &FindOwnerByIDParams{

		Context: ctx,
	}
}

// NewFindOwnerByIDParamsWithHTTPClient creates a new FindOwnerByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindOwnerByIDParamsWithHTTPClient(client *http.Client) *FindOwnerByIDParams {
	var ()
	return &FindOwnerByIDParams{
		HTTPClient: client,
	}
}

/*FindOwnerByIDParams contains all the parameters to send to the API endpoint
for the find owner by id operation typically these are written to a http.Request
*/
type FindOwnerByIDParams struct {

	/*ID
	  ID of an owner to fetch

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find owner by id params
func (o *FindOwnerByIDParams) WithTimeout(timeout time.Duration) *FindOwnerByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find owner by id params
func (o *FindOwnerByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find owner by id params
func (o *FindOwnerByIDParams) WithContext(ctx context.Context) *FindOwnerByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find owner by id params
func (o *FindOwnerByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find owner by id params
func (o *FindOwnerByIDParams) WithHTTPClient(client *http.Client) *FindOwnerByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find owner by id params
func (o *FindOwnerByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find owner by id params
func (o *FindOwnerByIDParams) WithID(id strfmt.UUID) *FindOwnerByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find owner by id params
func (o *FindOwnerByIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindOwnerByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
