// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scylladb/scylla-code-samples/iot-care-pet-example/go/cmd/server/models"
)

// FindOwnerByIDReader is a Reader for the FindOwnerByID structure.
type FindOwnerByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindOwnerByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindOwnerByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindOwnerByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindOwnerByIDOK creates a FindOwnerByIDOK with default headers values
func NewFindOwnerByIDOK() *FindOwnerByIDOK {
	return &FindOwnerByIDOK{}
}

/*FindOwnerByIDOK handles this case with default header values.

owner response
*/
type FindOwnerByIDOK struct {
	Payload *models.Owner
}

func (o *FindOwnerByIDOK) Error() string {
	return fmt.Sprintf("[GET /owner/{id}][%d] findOwnerByIdOK  %+v", 200, o.Payload)
}

func (o *FindOwnerByIDOK) GetPayload() *models.Owner {
	return o.Payload
}

func (o *FindOwnerByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Owner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindOwnerByIDDefault creates a FindOwnerByIDDefault with default headers values
func NewFindOwnerByIDDefault(code int) *FindOwnerByIDDefault {
	return &FindOwnerByIDDefault{
		_statusCode: code,
	}
}

/*FindOwnerByIDDefault handles this case with default header values.

error
*/
type FindOwnerByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the find owner by id default response
func (o *FindOwnerByIDDefault) Code() int {
	return o._statusCode
}

func (o *FindOwnerByIDDefault) Error() string {
	return fmt.Sprintf("[GET /owner/{id}][%d] find owner by id default  %+v", o._statusCode, o.Payload)
}

func (o *FindOwnerByIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *FindOwnerByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
