// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindSensorAvgBySensorIDAndDayParams creates a new FindSensorAvgBySensorIDAndDayParams object
// with the default values initialized.
func NewFindSensorAvgBySensorIDAndDayParams() *FindSensorAvgBySensorIDAndDayParams {
	var ()
	return &FindSensorAvgBySensorIDAndDayParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindSensorAvgBySensorIDAndDayParamsWithTimeout creates a new FindSensorAvgBySensorIDAndDayParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindSensorAvgBySensorIDAndDayParamsWithTimeout(timeout time.Duration) *FindSensorAvgBySensorIDAndDayParams {
	var ()
	return &FindSensorAvgBySensorIDAndDayParams{

		timeout: timeout,
	}
}

// NewFindSensorAvgBySensorIDAndDayParamsWithContext creates a new FindSensorAvgBySensorIDAndDayParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindSensorAvgBySensorIDAndDayParamsWithContext(ctx context.Context) *FindSensorAvgBySensorIDAndDayParams {
	var ()
	return &FindSensorAvgBySensorIDAndDayParams{

		Context: ctx,
	}
}

// NewFindSensorAvgBySensorIDAndDayParamsWithHTTPClient creates a new FindSensorAvgBySensorIDAndDayParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindSensorAvgBySensorIDAndDayParamsWithHTTPClient(client *http.Client) *FindSensorAvgBySensorIDAndDayParams {
	var ()
	return &FindSensorAvgBySensorIDAndDayParams{
		HTTPClient: client,
	}
}

/*FindSensorAvgBySensorIDAndDayParams contains all the parameters to send to the API endpoint
for the find sensor avg by sensor id and day operation typically these are written to a http.Request
*/
type FindSensorAvgBySensorIDAndDayParams struct {

	/*Day
	  average on a day

	*/
	Day strfmt.Date
	/*ID
	  ID of a sensor to fetch

	*/
	ID strfmt.UUID
	/*P
	  sensor parameter id

	*/
	P strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) WithTimeout(timeout time.Duration) *FindSensorAvgBySensorIDAndDayParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) WithContext(ctx context.Context) *FindSensorAvgBySensorIDAndDayParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) WithHTTPClient(client *http.Client) *FindSensorAvgBySensorIDAndDayParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDay adds the day to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) WithDay(day strfmt.Date) *FindSensorAvgBySensorIDAndDayParams {
	o.SetDay(day)
	return o
}

// SetDay adds the day to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) SetDay(day strfmt.Date) {
	o.Day = day
}

// WithID adds the id to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) WithID(id strfmt.UUID) *FindSensorAvgBySensorIDAndDayParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithP adds the p to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) WithP(p strfmt.UUID) *FindSensorAvgBySensorIDAndDayParams {
	o.SetP(p)
	return o
}

// SetP adds the p to the find sensor avg by sensor id and day params
func (o *FindSensorAvgBySensorIDAndDayParams) SetP(p strfmt.UUID) {
	o.P = p
}

// WriteToRequest writes these params to a swagger request
func (o *FindSensorAvgBySensorIDAndDayParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param day
	if err := r.SetPathParam("day", o.Day.String()); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// path param p
	if err := r.SetPathParam("p", o.P.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
