// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/scylladb/scylla-code-samples/iot-care-pet-example/go/cmd/server/models"
)

// FindPetsByOwnerIDReader is a Reader for the FindPetsByOwnerID structure.
type FindPetsByOwnerIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FindPetsByOwnerIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFindPetsByOwnerIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewFindPetsByOwnerIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFindPetsByOwnerIDOK creates a FindPetsByOwnerIDOK with default headers values
func NewFindPetsByOwnerIDOK() *FindPetsByOwnerIDOK {
	return &FindPetsByOwnerIDOK{}
}

/*FindPetsByOwnerIDOK handles this case with default header values.

pets response
*/
type FindPetsByOwnerIDOK struct {
	Payload []*models.Pet
}

func (o *FindPetsByOwnerIDOK) Error() string {
	return fmt.Sprintf("[GET /owner/{id}/pets][%d] findPetsByOwnerIdOK  %+v", 200, o.Payload)
}

func (o *FindPetsByOwnerIDOK) GetPayload() []*models.Pet {
	return o.Payload
}

func (o *FindPetsByOwnerIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFindPetsByOwnerIDDefault creates a FindPetsByOwnerIDDefault with default headers values
func NewFindPetsByOwnerIDDefault(code int) *FindPetsByOwnerIDDefault {
	return &FindPetsByOwnerIDDefault{
		_statusCode: code,
	}
}

/*FindPetsByOwnerIDDefault handles this case with default header values.

error
*/
type FindPetsByOwnerIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the find pets by owner id default response
func (o *FindPetsByOwnerIDDefault) Code() int {
	return o._statusCode
}

func (o *FindPetsByOwnerIDDefault) Error() string {
	return fmt.Sprintf("[GET /owner/{id}/pets][%d] find pets by owner id default  %+v", o._statusCode, o.Payload)
}

func (o *FindPetsByOwnerIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *FindPetsByOwnerIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
