// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindSensorsByPetIDParams creates a new FindSensorsByPetIDParams object
// with the default values initialized.
func NewFindSensorsByPetIDParams() *FindSensorsByPetIDParams {
	var ()
	return &FindSensorsByPetIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFindSensorsByPetIDParamsWithTimeout creates a new FindSensorsByPetIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFindSensorsByPetIDParamsWithTimeout(timeout time.Duration) *FindSensorsByPetIDParams {
	var ()
	return &FindSensorsByPetIDParams{

		timeout: timeout,
	}
}

// NewFindSensorsByPetIDParamsWithContext creates a new FindSensorsByPetIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewFindSensorsByPetIDParamsWithContext(ctx context.Context) *FindSensorsByPetIDParams {
	var ()
	return &FindSensorsByPetIDParams{

		Context: ctx,
	}
}

// NewFindSensorsByPetIDParamsWithHTTPClient creates a new FindSensorsByPetIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFindSensorsByPetIDParamsWithHTTPClient(client *http.Client) *FindSensorsByPetIDParams {
	var ()
	return &FindSensorsByPetIDParams{
		HTTPClient: client,
	}
}

/*FindSensorsByPetIDParams contains all the parameters to send to the API endpoint
for the find sensors by pet id operation typically these are written to a http.Request
*/
type FindSensorsByPetIDParams struct {

	/*ID
	  ID of a pet sensors to fetch

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) WithTimeout(timeout time.Duration) *FindSensorsByPetIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) WithContext(ctx context.Context) *FindSensorsByPetIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) WithHTTPClient(client *http.Client) *FindSensorsByPetIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) WithID(id strfmt.UUID) *FindSensorsByPetIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find sensors by pet id params
func (o *FindSensorsByPetIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindSensorsByPetIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
