version: '3'

services:
  scylladb-node1:
    image: scylladb/scylla:2.2.0
    networks:
      - scylla
    volumes:
      - ./data/node1:/var/lib/scylla
    command: "--seeds scylladb-node1,scylladb-node2,scylladb-node3 --smp 1 --memory 256M"
  scylladb-node2:
    image: scylladb/scylla:2.2.0
    networks:
      - scylla
    volumes:
      - ./data/node2:/var/lib/scylla
    command: "--seeds scylladb-node1,scylladb-node2,scylladb-node3 --smp 1 --memory 256M"
  scylladb-node3:
    image: scylladb/scylla:2.2.0
    networks:
      - scylla
    volumes:
      - ./data/node3:/var/lib/scylla
    command: "--seeds scylladb-node1,scylladb-node2,scylladb-node3 --smp 1 --memory 256M"

  spark-master:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: spark-master
    networks:
      - scylla
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./data/spark-master:/tmp/data

  spark-worker:
    image: gettyimages/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1024m
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: spark-worker
    networks:
      - scylla
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./data/spark-worker:/tmp/data
    depends_on:
      - spark-master

networks:
  scylla:
