// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Care Pet monitoring system",
    "title": "Care Pet",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/owner/{id}": {
      "get": {
        "description": "Find an owner with a specific ID",
        "operationId": "find owner by id",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of an owner to fetch",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "owner response",
            "schema": {
              "$ref": "#/definitions/Owner"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/owner/{id}/pets": {
      "get": {
        "description": "Find the Pets that the owner tracks",
        "operationId": "find pets by owner id",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of an owner pets to fetch",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "pets response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/pet/{id}/sensors": {
      "get": {
        "description": "Find the Pet sensors",
        "operationId": "find sensors by pet id",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of a pet sensors to fetch",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "sensors response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Sensor"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/sensor/{id}/values": {
      "get": {
        "description": "Read sensor data",
        "operationId": "find sensor data by sensor id and time range",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of a sensor to fetch",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "from timestamp",
            "name": "from",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "to timestamp",
            "name": "to",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "sensors response",
            "schema": {
              "type": "array",
              "items": {
                "type": "number",
                "format": "float"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/sensor/{id}/values/day/{day}": {
      "get": {
        "description": "Find a daily summary of hour based aggregates",
        "operationId": "find sensor avg by sensor id and day",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of a sensor to fetch",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "format": "date",
            "description": "average on a day",
            "name": "day",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "sensor avg response",
            "schema": {
              "type": "array",
              "items": {
                "type": "number",
                "format": "float"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Measure": {
      "type": "object",
      "required": [
        "sensor_id"
      ],
      "properties": {
        "sensor_id": {
          "type": "string",
          "format": "uuid"
        },
        "ts": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      }
    },
    "Owner": {
      "type": "object",
      "required": [
        "owner_id"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "owner_id": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "Pet": {
      "type": "object",
      "required": [
        "owner_id",
        "pet_id"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "owner_id": {
          "type": "string",
          "format": "uuid"
        },
        "pet_id": {
          "type": "string",
          "format": "uuid"
        },
        "weight": {
          "type": "number"
        }
      }
    },
    "Sensor": {
      "type": "object",
      "required": [
        "pet_id",
        "sensor_id"
      ],
      "properties": {
        "pet_id": {
          "type": "string",
          "format": "uuid"
        },
        "sensor_id": {
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "SensorAvg": {
      "type": "object",
      "required": [
        "sensor_id"
      ],
      "properties": {
        "date": {
          "type": "string"
        },
        "hour": {
          "type": "number"
        },
        "sensor_id": {
          "type": "string",
          "format": "uuid"
        },
        "value": {
          "type": "number"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Care Pet monitoring system",
    "title": "Care Pet",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/owner/{id}": {
      "get": {
        "description": "Find an owner with a specific ID",
        "operationId": "find owner by id",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of an owner to fetch",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "owner response",
            "schema": {
              "$ref": "#/definitions/Owner"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/owner/{id}/pets": {
      "get": {
        "description": "Find the Pets that the owner tracks",
        "operationId": "find pets by owner id",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of an owner pets to fetch",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "pets response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Pet"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/pet/{id}/sensors": {
      "get": {
        "description": "Find the Pet sensors",
        "operationId": "find sensors by pet id",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of a pet sensors to fetch",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "sensors response",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Sensor"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/sensor/{id}/values": {
      "get": {
        "description": "Read sensor data",
        "operationId": "find sensor data by sensor id and time range",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of a sensor to fetch",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "from timestamp",
            "name": "from",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "format": "date-time",
            "description": "to timestamp",
            "name": "to",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "sensors response",
            "schema": {
              "type": "array",
              "items": {
                "type": "number",
                "format": "float"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/sensor/{id}/values/day/{day}": {
      "get": {
        "description": "Find a daily summary of hour based aggregates",
        "operationId": "find sensor avg by sensor id and day",
        "parameters": [
          {
            "type": "string",
            "format": "uuid",
            "description": "ID of a sensor to fetch",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "format": "date",
            "description": "average on a day",
            "name": "day",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "sensor avg response",
            "schema": {
              "type": "array",
              "items": {
                "type": "number",
                "format": "float"
              }
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Measure": {
      "type": "object",
      "required": [
        "sensor_id"
      ],
      "properties": {
        "sensor_id": {
          "type": "string",
          "format": "uuid"
        },
        "ts": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      }
    },
    "Owner": {
      "type": "object",
      "required": [
        "owner_id"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "owner_id": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "Pet": {
      "type": "object",
      "required": [
        "owner_id",
        "pet_id"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "age": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "owner_id": {
          "type": "string",
          "format": "uuid"
        },
        "pet_id": {
          "type": "string",
          "format": "uuid"
        },
        "weight": {
          "type": "number"
        }
      }
    },
    "Sensor": {
      "type": "object",
      "required": [
        "pet_id",
        "sensor_id"
      ],
      "properties": {
        "pet_id": {
          "type": "string",
          "format": "uuid"
        },
        "sensor_id": {
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "SensorAvg": {
      "type": "object",
      "required": [
        "sensor_id"
      ],
      "properties": {
        "date": {
          "type": "string"
        },
        "hour": {
          "type": "number"
        },
        "sensor_id": {
          "type": "string",
          "format": "uuid"
        },
        "value": {
          "type": "number"
        }
      }
    }
  }
}`))
}
