// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Measure measure
//
// swagger:model Measure
type Measure struct {

	// sensor id
	// Required: true
	// Format: uuid
	SensorID *strfmt.UUID `json:"sensor_id"`

	// ts
	Ts string `json:"ts,omitempty"`

	// value
	Value float64 `json:"value,omitempty"`
}

// Validate validates this measure
func (m *Measure) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSensorID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Measure) validateSensorID(formats strfmt.Registry) error {

	if err := validate.Required("sensor_id", "body", m.SensorID); err != nil {
		return err
	}

	if err := validate.FormatOf("sensor_id", "body", "uuid", m.SensorID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Measure) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Measure) UnmarshalBinary(b []byte) error {
	var res Measure
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
