// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Pet pet
//
// swagger:model Pet
type Pet struct {

	// address
	Address string `json:"address,omitempty"`

	// age
	Age int64 `json:"age,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// owner id
	// Required: true
	// Format: uuid
	OwnerID *strfmt.UUID `json:"owner_id"`

	// pet id
	// Required: true
	// Format: uuid
	PetID *strfmt.UUID `json:"pet_id"`

	// weight
	Weight float64 `json:"weight,omitempty"`
}

// Validate validates this pet
func (m *Pet) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOwnerID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePetID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Pet) validateOwnerID(formats strfmt.Registry) error {

	if err := validate.Required("owner_id", "body", m.OwnerID); err != nil {
		return err
	}

	if err := validate.FormatOf("owner_id", "body", "uuid", m.OwnerID.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Pet) validatePetID(formats strfmt.Registry) error {

	if err := validate.Required("pet_id", "body", m.PetID); err != nil {
		return err
	}

	if err := validate.FormatOf("pet_id", "body", "uuid", m.PetID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Pet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pet) UnmarshalBinary(b []byte) error {
	var res Pet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
