// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SensorAvg sensor avg
//
// swagger:model SensorAvg
type SensorAvg struct {

	// date
	Date string `json:"date,omitempty"`

	// hour
	Hour float64 `json:"hour,omitempty"`

	// sensor id
	// Required: true
	// Format: uuid
	SensorID *strfmt.UUID `json:"sensor_id"`

	// value
	Value float64 `json:"value,omitempty"`
}

// Validate validates this sensor avg
func (m *SensorAvg) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSensorID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SensorAvg) validateSensorID(formats strfmt.Registry) error {

	if err := validate.Required("sensor_id", "body", m.SensorID); err != nil {
		return err
	}

	if err := validate.FormatOf("sensor_id", "body", "uuid", m.SensorID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SensorAvg) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SensorAvg) UnmarshalBinary(b []byte) error {
	var res SensorAvg
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
